version: '3.3'
services:
  mongo_db:
    image: mongo:3.2.21
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports: 
      - 27017:27017/tcp
    volumes:
      - mongo_db:/data/db
    networks:
      - front_net
      - back_net
  ui:
    build: ./dev/ui
    image: zoolgle/crawler_ui:1.0
    ports:
      - 8000:8000/tcp
    depends_on: 
      - mongo_db
      - rabbitmq
    networks:
      - front_net
  crawler:
    build: ./dev/crawler
    image: zoolgle/crawler:1.0
    ports: 
      - 8000:8000/tcp
    depends_on: 
      - mongo_db
      - rabbitmq
    networks:
      - back_net
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 5672:5672/tcp
      - 15672:15672/tcp
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - back_net
  prometheus:
    image: prom/prometheus:latest
    networks: 
      - front_net
      - back_net

volumes:
  mongo_db:

networks:
  front_net:
  back_net:
